/**
 * LMS service.
 *
 * Owns enrollment lifecycle, lesson scoring, attempt + cooldown
 * enforcement, certificate generation, and the signed mobile-→-web
 * deep-link round trip. The signed JWT is the single auth token the
 * web LMS page uses to read the user's enrollment + lesson content;
 * it expires in 15 minutes so a leaked link can't be replayed.
 *
 * On a passing final-lesson submission we:
 *   1. Mark the enrollment PASSED
 *   2. Render + upload the certificate PDF
 *   3. Persist certificateKey + certificateIssuedAt
 *   4. Flip ProviderServiceEligibility.trainingPassed for every service
 *      whose requiredCourseId matches this course
 *   5. Emit `provider.training_completed`
 *
 * All five steps run inside a single Prisma transaction so the
 * enrollment + eligibility flip + audit log can never desync. The
 * certificate upload happens *outside* the transaction (a network call
 * to Cloudinary) — if that fails the user is still PASSED and the
 * certificate can be regenerated by a retry endpoint later.
 */
import {
  Injectable,
  NotFoundException,
  ForbiddenException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { EventEmitter2 } from '@nestjs/event-emitter';
import {
  CourseId,
  CourseStatus,
  LessonType,
  ProviderEligibilityAuditAction,
} from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { UploadsService } from '../uploads/uploads.service';
import { CertificateService } from './certificate.service';
import { CompleteLessonDto } from './lms.dto';
import { isSandbox, SANDBOX_CONFIG } from '../../common/sandbox/sandbox.config';

const WEB_LINK_TTL_SECONDS = 900; // 15 min — matches CONVENTIONS doc TTL ceiling

@Injectable()
export class LmsService {
  private readonly logger = new Logger(LmsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly uploads: UploadsService,
    private readonly certificates: CertificateService,
    private readonly jwtService: JwtService,
    private readonly config: ConfigService,
    private readonly eventEmitter: EventEmitter2,
  ) {}

  // ── Discovery ──────────────────────────────────────────────────────────────

  /**
   * Returns every course the provider needs (i.e. has an eligibility row
   * referencing) plus their enrollment status.
   */
  async getCoursesForProvider(providerId: string) {
    const eligibilities = await this.prisma.providerServiceEligibility.findMany({
      where: { providerId, trainingRequired: true },
      select: { requiredCourseId: true, serviceType: true },
    });
    const requiredCourseIds = Array.from(
      new Set(
        eligibilities
          .map((e) => e.requiredCourseId)
          .filter((id): id is string => !!id),
      ),
    );

    if (!requiredCourseIds.length) return [];

    const courses = await this.prisma.course.findMany({
      where: { id: { in: requiredCourseIds as CourseId[] }, isActive: true },
      include: {
        enrollments: {
          where: { providerId },
          select: {
            status: true,
            currentLesson: true,
            score: true,
            attempts: true,
            lastAttemptAt: true,
            certificateKey: true,
            completedAt: true,
          },
        },
      },
    });

    return courses.map((c) => ({
      ...c,
      enrollment: c.enrollments[0] ?? null,
    }));
  }

  /** Returns the course + lessons + question metadata for the player. */
  async getCourseDetail(providerId: string, courseId: CourseId) {
    const course = await this.prisma.course.findUnique({
      where: { id: courseId },
      include: {
        lessons: {
          orderBy: { order: 'asc' },
          include: {
            questions: { orderBy: { order: 'asc' } },
          },
        },
      },
    });
    if (!course) throw new NotFoundException('Course not found.');

    const enrollment = await this.prisma.courseEnrollment.findUnique({
      where: { providerId_courseId: { providerId, courseId } },
      include: { progress: true },
    });

    // Mobile uses this URL to render the "Skip course (sandbox)" button
    // without hardcoding the path on the client.
    const sandbox = isSandbox()
      ? { sandboxCompleteUrl: '/lms/sandbox/complete-course' }
      : {};

    return { course, enrollment, ...sandbox };
  }

  // ── Enrollment ─────────────────────────────────────────────────────────────

  async enroll(providerId: string, courseId: CourseId) {
    const course = await this.prisma.course.findUnique({
      where: { id: courseId },
      select: { id: true, isActive: true },
    });
    if (!course || !course.isActive) {
      throw new NotFoundException('Course not found or inactive.');
    }

    return this.prisma.courseEnrollment.upsert({
      where: { providerId_courseId: { providerId, courseId } },
      create: {
        providerId,
        courseId,
        status: CourseStatus.IN_PROGRESS,
        startedAt: new Date(),
        currentLesson: 1,
      },
      update: {
        // Re-enrolling after a FAILED attempt resets to IN_PROGRESS so
        // the player picks the user up at lesson 1 again. We do NOT
        // reset attempts — cooldown guards live on the attempt counter.
        status: CourseStatus.IN_PROGRESS,
        startedAt: new Date(),
      },
    });
  }

  // ── Lesson completion + scoring ────────────────────────────────────────────

  async completeLesson(
    providerId: string,
    courseId: CourseId,
    lessonOrder: number,
    dto: CompleteLessonDto,
  ) {
    // Hydrate everything we need in two reads so the transaction below
    // is just writes.
    const enrollment = await this.prisma.courseEnrollment.findUnique({
      where: { providerId_courseId: { providerId, courseId } },
      include: { course: true },
    });
    if (!enrollment) {
      throw new NotFoundException('Enroll in the course before completing lessons.');
    }

    if (enrollment.status === CourseStatus.PASSED) {
      // Idempotent — the player can redirect back here after a deep-link
      // round trip without re-issuing a certificate.
      return { status: enrollment.status, score: enrollment.score };
    }

    if (lessonOrder < enrollment.currentLesson) {
      throw new BadRequestException('Lesson already completed.');
    }
    if (lessonOrder > enrollment.currentLesson) {
      throw new BadRequestException('Cannot skip ahead. Complete the current lesson first.');
    }

    const lesson = await this.prisma.courseLesson.findUnique({
      where: {
        courseId_order: { courseId, order: lessonOrder },
      },
      include: { questions: true },
    });
    if (!lesson) throw new NotFoundException('Lesson not found.');

    let quizScore: number | null = null;

    if (lesson.type === LessonType.QUIZ) {
      const answers = dto.answers ?? {};
      const total = lesson.questions.length;
      if (total === 0) {
        throw new BadRequestException('Quiz has no questions configured.');
      }
      const correct = lesson.questions.reduce((acc, q) => {
        return acc + (answers[q.id] === q.correctId ? 1 : 0);
      }, 0);
      quizScore = Math.round((correct / total) * 100);
    }

    const isFinalLesson = lessonOrder === enrollment.course.totalLessons;
    const passScore = enrollment.course.passScore;
    const passed =
      isFinalLesson &&
      lesson.type === LessonType.QUIZ &&
      (quizScore ?? 0) >= passScore;
    const failed =
      isFinalLesson &&
      lesson.type === LessonType.QUIZ &&
      (quizScore ?? 0) < passScore;

    // Cooldown / max-attempts gate runs before the write so a user who
    // exhausted attempts can't wedge new progress in.
    if (failed) {
      const attempts = enrollment.attempts + 1;
      if (attempts >= enrollment.course.maxAttempts) {
        const cooldownMs = enrollment.course.cooldownHours * 60 * 60 * 1000;
        const cooldownUntil = enrollment.lastAttemptAt
          ? new Date(enrollment.lastAttemptAt.getTime() + cooldownMs)
          : new Date(Date.now() + cooldownMs);
        if (cooldownUntil.getTime() > Date.now()) {
          throw new ForbiddenException({
            code: 'COURSE_COOLDOWN',
            messageEn: 'Try again after the cooldown period.',
            messageAr: 'حاول مرة أخرى بعد فترة الانتظار.',
            cooldownUntil: cooldownUntil.toISOString(),
          });
        }
      }
    }

    // Persist progress + status flip in a single transaction. Certificate
    // upload (network call) is intentionally outside.
    const updated = await this.prisma.$transaction(async (tx) => {
      await tx.lessonProgress.upsert({
        where: {
          enrollmentId_lessonOrder: {
            enrollmentId: enrollment.id,
            lessonOrder,
          },
        },
        create: {
          enrollmentId: enrollment.id,
          lessonOrder,
          completedAt: new Date(),
          quizScore,
        },
        update: {
          completedAt: new Date(),
          quizScore,
        },
      });

      const data: Record<string, unknown> = {
        currentLesson: isFinalLesson
          ? enrollment.currentLesson
          : enrollment.currentLesson + 1,
        lastAttemptAt: lesson.type === LessonType.QUIZ ? new Date() : enrollment.lastAttemptAt,
      };

      if (lesson.type === LessonType.QUIZ && isFinalLesson) {
        data.score = quizScore;
        data.attempts = enrollment.attempts + 1;
        if (passed) {
          data.status = CourseStatus.PASSED;
          data.completedAt = new Date();
        } else {
          data.status = CourseStatus.FAILED;
        }
      } else if (enrollment.status === CourseStatus.NOT_STARTED) {
        data.status = CourseStatus.IN_PROGRESS;
        data.startedAt = enrollment.startedAt ?? new Date();
      }

      return tx.courseEnrollment.update({
        where: { id: enrollment.id },
        data,
        include: { course: true },
      });
    });

    if (passed) {
      // Side-effects: certificate, eligibility flip, audit log, event.
      // Done outside the inner tx so a Cloudinary failure doesn't roll
      // back PASSED. We can backfill certs from a CRON/retry path.
      await this.handleCoursePassed(updated);
    }

    return {
      status: updated.status,
      score: updated.score,
      currentLesson: updated.currentLesson,
      attempts: updated.attempts,
      passed,
      passScore,
    };
  }

  // ── Pass side-effects ──────────────────────────────────────────────────────

  private async handleCoursePassed(enrollment: {
    id: string;
    providerId: string;
    courseId: CourseId;
    score: number | null;
  }) {
    // 1. Generate + upload certificate (best-effort — failures are logged
    //    but don't roll back the PASSED status).
    let certificateKey: string | null = null;
    try {
      const provider = await this.prisma.user.findUnique({
        where: { id: enrollment.providerId },
        select: { firstName: true, lastName: true },
      });
      const course = await this.prisma.course.findUnique({
        where: { id: enrollment.courseId },
        select: { titleEn: true, titleAr: true },
      });
      if (provider && course) {
        certificateKey = await this.certificates.generateCertificate({
          providerId: enrollment.providerId,
          providerName: `${provider.firstName ?? ''} ${provider.lastName ?? ''}`.trim() || 'Provider',
          courseId: enrollment.courseId,
          courseTitleEn: course.titleEn,
          courseTitleAr: course.titleAr,
          score: enrollment.score ?? 0,
          issuedAt: new Date(),
        });
      }
    } catch (err: any) {
      this.logger.error(
        `Certificate generation failed for ${enrollment.providerId}/${enrollment.courseId}: ${err?.message}`,
      );
    }

    // 2. Persist certificate + flip eligibility, all in one tx.
    await this.prisma.$transaction(async (tx) => {
      if (certificateKey) {
        await tx.courseEnrollment.update({
          where: { id: enrollment.id },
          data: {
            certificateKey,
            certificateIssuedAt: new Date(),
          },
        });
      }

      // Flip trainingPassed on every eligibility row whose
      // requiredCourseId matches this course. A provider with WALKING +
      // BOARDING who passed BOARDING_PROVIDER_COURSE will see both rows
      // flip because both reference the boarding course id.
      const flipped = await tx.providerServiceEligibility.updateMany({
        where: {
          providerId: enrollment.providerId,
          requiredCourseId: enrollment.courseId,
          trainingPassed: false,
        },
        data: {
          trainingPassed: true,
          trainingScore: enrollment.score ?? 0,
          trainingCompletedAt: new Date(),
          certificateKey: certificateKey ?? undefined,
        },
      });

      if (flipped.count > 0) {
        const rows = await tx.providerServiceEligibility.findMany({
          where: {
            providerId: enrollment.providerId,
            requiredCourseId: enrollment.courseId,
          },
          select: { id: true },
        });
        await tx.providerServiceEligibilityAuditLog.createMany({
          data: rows.map((r) => ({
            eligibilityId: r.id,
            actorUserId: enrollment.providerId,
            action: ProviderEligibilityAuditAction.TRAINING_COMPLETED,
            metadata: {
              courseId: enrollment.courseId,
              score: enrollment.score,
              certificateKey,
            },
          })),
        });
      }
    });

    this.eventEmitter.emit('provider.training_completed', {
      providerId: enrollment.providerId,
      courseId: enrollment.courseId,
      score: enrollment.score,
    });
  }

  // ── Certificate signed URL ────────────────────────────────────────────────

  async getCertificateUrl(providerId: string, courseId: CourseId) {
    const enrollment = await this.prisma.courseEnrollment.findUnique({
      where: { providerId_courseId: { providerId, courseId } },
      select: { certificateKey: true, certificateIssuedAt: true, status: true },
    });
    if (!enrollment) {
      throw new NotFoundException('No enrollment found.');
    }
    if (enrollment.status !== CourseStatus.PASSED || !enrollment.certificateKey) {
      throw new NotFoundException('Certificate not yet issued for this course.');
    }
    const signed = this.uploads.signedUrlFor(enrollment.certificateKey, {
      ttlSeconds: 900,
      resourceType: 'raw',
    });
    return {
      url: signed.url,
      expiresAt: signed.expiresAt.toISOString(),
      issuedAt: enrollment.certificateIssuedAt?.toISOString() ?? null,
    };
  }

  // ── Sandbox: force-pass a course ──────────────────────────────────────────

  /**
   * SANDBOX ONLY — force-completes a course for the calling provider
   * without watching any lessons. Mirrors the side-effects of a real
   * passing final-lesson submission so the eligibility flip + audit log
   * stay consistent.
   *
   * The controller gates this on isSandbox(); the extra check here is a
   * defence-in-depth guard so a misconfigured production server can't
   * accidentally hand out certificates.
   */
  async sandboxCompleteCourse(providerId: string, courseId: CourseId) {
    if (!isSandbox()) {
      throw new ForbiddenException('Sandbox endpoints are disabled.');
    }

    const course = await this.prisma.course.findUnique({
      where: { id: courseId },
      select: { id: true, isActive: true },
    });
    if (!course || !course.isActive) {
      throw new NotFoundException('Course not found or inactive.');
    }

    const score = SANDBOX_CONFIG.sandboxScore;
    const now = new Date();

    const enrollment = await this.prisma.courseEnrollment.upsert({
      where: { providerId_courseId: { providerId, courseId } },
      create: {
        providerId,
        courseId,
        status: CourseStatus.PASSED,
        startedAt: now,
        completedAt: now,
        currentLesson: 1,
        score,
        attempts: 1,
        lastAttemptAt: now,
        certificateKey: `sandbox:${providerId}:${courseId}`,
        certificateIssuedAt: now,
      },
      update: {
        status: CourseStatus.PASSED,
        completedAt: now,
        score,
        lastAttemptAt: now,
        certificateKey: `sandbox:${providerId}:${courseId}`,
        certificateIssuedAt: now,
      },
    });

    // Flip every matching eligibility row to trainingPassed. Mirrors the
    // real handleCoursePassed side-effect.
    await this.prisma.providerServiceEligibility.updateMany({
      where: {
        providerId,
        requiredCourseId: courseId,
      },
      data: {
        trainingPassed: true,
        trainingScore: score,
        trainingCompletedAt: now,
        certificateKey: `sandbox:${providerId}:${courseId}`,
      },
    });

    this.eventEmitter.emit('provider.training_completed', {
      providerId,
      courseId,
      score,
      sandbox: true,
    });

    return {
      passed: true,
      score,
      sandbox: true,
      certificateLabel: SANDBOX_CONFIG.sandboxCertificateLabel,
      enrollmentId: enrollment.id,
    };
  }

  // ── Web deep-link ──────────────────────────────────────────────────────────

  /**
   * Mints a 15-min signed JWT bound to (providerId, courseId, aud=lms-web)
   * and returns the web URL the mobile app should open. The web LMS page
   * verifies the JWT against JWT_SECRET, loads the enrollment, and
   * deep-links the user back to the mobile app on completion via the
   * returned `returnUrl`.
   */
  buildWebLink(providerId: string, courseId: CourseId) {
    const secret = this.config.get<string>('JWT_SECRET');
    if (!secret) {
      throw new BadRequestException('LMS web link is not configured (missing secret).');
    }
    const token = this.jwtService.sign(
      { sub: providerId, courseId, aud: 'lms-web' },
      { secret, expiresIn: WEB_LINK_TTL_SECONDS },
    );

    const webBase =
      this.config.get<string>('LMS_WEB_BASE_URL') ?? 'https://pawmatehub.com';
    const mobileScheme =
      this.config.get<string>('MOBILE_DEEP_LINK_SCHEME') ?? 'pawmatehub';

    const webUrl = `${webBase}/learn/${courseId}?token=${token}`;
    const returnUrl = `${mobileScheme}://onboarding?courseId=${courseId}&status=completed`;
    const expiresAt = new Date(Date.now() + WEB_LINK_TTL_SECONDS * 1000);

    return { webUrl, returnUrl, expiresAt: expiresAt.toISOString() };
  }
}
